// src/app/home/home.component.ts
import { Component, OnInit, OnDestroy, ElementRef, ViewChild, inject } from '@angular/core';
import { PageTitleComponent } from '../components/page-title/page-title.component';
import { PageTitleService } from '../services/page-title.service';

@Component({
    standalone: true,
    imports: [PageTitleComponent],
    selector: 'app-home',
    templateUrl: 'home.component.html',
    styleUrl: 'home.component.scss',
})

export class HomeComponent implements OnInit, OnDestroy {
    @ViewChild('slides', { static: true }) slides!: ElementRef<HTMLDivElement>;
    @ViewChild('slider', { static: true }) slider!: ElementRef<HTMLDivElement>;

    currentIndex = 0;
    autoPlayInterval: any;
    private pageTitleService = inject(PageTitleService);

    photos = [
        {
            avif: 'https://cdn.jsdelivr.net/gh/filin121666/about_me@gh-pages/my_photo1/my_photo1.avif',
            webp: 'https://cdn.jsdelivr.net/gh/filin121666/about_me@gh-pages/my_photo1/my_photo1.webp',
            jpg: 'https://cdn.jsdelivr.net/gh/filin121666/about_me@gh-pages/my_photo1/my_photo1.jpg',
            alt: 'my photo 1',
        },
        {
            avif: 'https://cdn.jsdelivr.net/gh/filin121666/about_me@gh-pages/my_photo2/my_photo2.avif',
            webp: 'https://cdn.jsdelivr.net/gh/filin121666/about_me@gh-pages/my_photo2/my_photo2.webp',
            jpg: 'https://cdn.jsdelivr.net/gh/filin121666/about_me@gh-pages/my_photo2/my_photo2.jpg',
            alt: 'my photo 2',
        }
    ];

    async ngOnInit() {
        this.pageTitleService.setPageTitle('home');
        this.startAutoPlay();
        window.addEventListener('resize', () => {
            this.goToSlide(this.currentIndex);
        });
    }

    ngOnDestroy() {
        this.stopAutoPlay();;
        window.removeEventListener('resize', () => {
            this.goToSlide(this.currentIndex);
        });
    }

    goToSlide(index: number) {
        const slideCount = this.photos.length;
        
        if (index < 0) {
            index = slideCount - 1;
        } else if (index >= slideCount) {
            index = 0;
        }

        this.currentIndex = index;
        if (this.slides && this.slider) {
            const slideWidth = this.slider.nativeElement.offsetWidth;
            this.slides.nativeElement.style.transform = `translateX(${-index * slideWidth}px)`;
        }
    }

    goToPrev() {
        this.goToSlide(this.currentIndex - 1);
    }

    goToNext() {
        this.goToSlide(this.currentIndex + 1);
    }

    startAutoPlay() {
        this.stopAutoPlay();
        
        this.autoPlayInterval = setInterval(() => {
            this.goToSlide(this.currentIndex + 1);
        }, 8000);
    }

    stopAutoPlay() {
        if (this.autoPlayInterval) {
            clearInterval(this.autoPlayInterval);
        }
    }

    onMouseEnter(event?: Event) {
        this.stopAutoPlay();
    }

    onMouseLeave(event?: Event) {
        this.startAutoPlay();
    }

    onPhotoClick() {
        this.goToNext();
    }
}
<main class="home-page">
    <app-page-title>Главная</app-page-title>
    <div class="home-page-body">
        <section class="home-page-body-content">
            <picture class="home-page-body-content-greeting">
                <source srcset="/greeting.webp" type="image/webp">
                <img src="/greeting.gif" alt="greeting">
            </picture>
            <hr class="home-page-hr">
            <p class="home-page-body-content-text roboto-regular">
                Я, Шанин Кирилл Сергеевич, начинающий разработчик из
                России. Окончил 9 класс с красным аттестатом, сейчас продолжаю учиться в школе. 
                Занимаюсь Backend-разработкой на Python. Изучаю
                Python, C/C++ и Computer Science. Помимо
                программирования также увлекаюсь математикой и физикой.
            </p>
        </section>
        <section class="home-page-body-photo" (mouseenter)="onMouseEnter($event)" (mouseleave)="onMouseLeave($event)">
            <div class="home-page-body-photo-slider" #slider (click)="onPhotoClick()">
                <div class="home-page-body-photo-slider-slides" #slides>
                    @for (photo of photos; track photo.alt) {
                        <div class="home-page-body-photo-slider-slides-slide">
                            <picture class="home-page-body-photo-image">
                                <source [srcset]="photo.avif" type="image/avif">
                                <source [srcset]="photo.webp" type="image/webp">
                                <img [src]="photo.jpg" [alt]="photo.alt">
                            </picture>
                        </div>
                    }
                </div>
            </div>
        </section>
    </div>
</main>

// src/components/home/home.jsx
import "./home.css";
import Head from "../head/head.jsx";
import { useState } from "react";
import { useEffect } from "react";

// const photos = ["/my_photo1.jpg", "/my_photo2.jpg"];
// const photos = ["/about_me/my_photo1.jpg", "/about_me/my_photo2.jpg"];
const photos = [
    "https://cdn.jsdelivr.net/gh/filin121666/about_me@gh-pages/my_photo1.jpg",
    "https://cdn.jsdelivr.net/gh/filin121666/about_me@gh-pages/my_photo2.jpg",
];

function Home() {
    const [currentPhotoIndex, setCurrentPhotoIndex] = useState(0);
    const [fade, setFade] = useState(false);

    useEffect(() => {
        const intervalId = setInterval(() => {
            setFade(true);
            setTimeout(() => {
                setCurrentPhotoIndex(
                    (prevIndex) => (prevIndex + 1) % photos.length
                );
                setFade(false);
            }, 500);
        }, 3500);

        return () => clearInterval(intervalId);
    }, []);

    return (
        <section className="home">
            <Head>Обо мне</Head>
            <div className="home-content">
                <div className="home-content-description">
                    <div className="home-content-text-img">
                        <img
                            // src="/greeting.webp"
                            src="/about_me/greeting.webp"
                            alt="greeting"
                            className="home-content-text-greeting"
                        />
                    </div>
                    <p className="home-content-text roboto-regular">
                        Я, Шанин Кирилл Сергеевич, начинающий разработчик из
                        России. Занимаюсь Backend-разработкой на Python. Изучаю
                        Python, C/C++, Arduino C и Computer Science. Помимо
                        программирования также увлекаюсь математикой и физикой.
                    </p>
                </div>
                <div className="home-content-photo">
                    <img
                        src={photos[currentPhotoIndex]}
                        alt="my photo"
                        className={`home-content-photo-img ${
                            fade ? "fade-out" : "fade-in"
                        }`}
                    />
                </div>
            </div>
        </section>
    );
}

export default Home;
