// src/app/components/header/components/right-functional/components/navigation/navigation.component.ts
import { Component } from '@angular/core';

import { NavLinkComponent } from './nav-link/nav-link.component';

@Component({
    standalone: true,
    imports: [NavLinkComponent],
    selector: 'app-header-navigation',
    templateUrl: 'navigation.component.html',
    styleUrl: 'navigation.component.scss',
})

export class NavigationComponent {
    public isOpen: boolean = false;

    public toggleMenu(): void {
        this.isOpen = !this.isOpen;
    }

    public closeMenu(): void {
        this.isOpen = false;
    }

}
<nav class="navigation">
    <button class="menu-button" (click)="toggleMenu()" aria-label="Open navigation">
        <img src="https://cdn.jsdelivr.net/gh/filin121666/about_me@gh-pages/menu-button.svg" alt="menu" />
    </button>

    @if (isOpen) {
    <div class="backdrop" (click)="closeMenu()"></div>
    <ul class="menu-list">
        <li>
            <app-nav-link path="/home" (navigated)="closeMenu()">Главная</app-nav-link>
        </li>
        <li>
            <app-nav-link path="/skills" (navigated)="closeMenu()">Навыки</app-nav-link>
        </li>
        <li>
            <app-nav-link path="/achievements" (navigated)="closeMenu()">Достижения</app-nav-link>
        </li>
        <li>
            <app-nav-link path="/projects" (navigated)="closeMenu()">Проекты</app-nav-link>
        </li>
    </ul>
    }
</nav>

// src/components/header/navigation/navigation.jsx
import "./navigation.css";
import NavLinkButton from "./nav_link/nav_link.jsx";
import { useState, useEffect, useRef } from "react";

function Navigation({ page, setPage }) {
    const [isMenuOpen, setIsMenuOpen] = useState(false);
    const menuRef = useRef(null);
    const buttonRef = useRef(null);

    const toggleMenu = () => setIsMenuOpen(!isMenuOpen);

    const handleClickOutside = (event) => {
        if (menuRef.current && !menuRef.current.contains(event.target) &&
            buttonRef.current && !buttonRef.current.contains(event.target)) {
            setIsMenuOpen(false);
        }
    };

    useEffect(() => {
        document.addEventListener("mousedown", handleClickOutside);
        return () => {
            document.removeEventListener("mousedown", handleClickOutside);
        };
    }, []);

    return (
        <div className="navigation-container">
            <button className="menu-button" onClick={toggleMenu} ref={buttonRef}>
                {/* <img src="/menu-button.svg" alt="menu" className="menu-button-icon"/> */}
                <img src="/about_me/menu-button.svg" alt="menu" className="menu-button-icon"/>
            </button>
            <div className={`navigation ${isMenuOpen ? 'open' : ''}`} ref={menuRef}>
                <NavLinkButton
                    isActive={page === "home"}
                    onClick={() => setPage("home")}
                >
                    Главная
                </NavLinkButton>
                <NavLinkButton
                    isActive={page === "skills"}
                    onClick={() => setPage("skills")}
                >
                    Навыки, технологии и прочее
                </NavLinkButton>
                <NavLinkButton
                    isActive={page === "achievements"}
                    onClick={() => setPage("achievements")}
                >
                    Достижения
                </NavLinkButton>
                <NavLinkButton
                    isActive={page === "projects"}
                    onClick={() => setPage("projects")}
                >
                    Проекты
                </NavLinkButton>
            </div>
        </div>
    );
}

export default Navigation;
